flartaux/dossier/routes.py
"""
from dotenv import load_dotenv
load_dotenv()

from flask import Flask
from config import Config
from models import db
"""
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
#from models import db, TDemande
#from ..extensions import db, TDemande

#from extensions import db
#from app import db
#from models import db
from models import db, TParceldem, TDemande, Users, TUsager   # importer le modèle
#from extensions import db     # importer la même instance db

from flask import Blueprint, render_template
#dossier = Blueprint('dossier_blueprint', __name__)

# Create the Blueprint instance
#dossier_blueprint = Blueprint('dossier_blueprint', __name__)
dossier = Blueprint('dossier', __name__)
from . import dossier
from sqlalchemy import text
# Import routes to connect with the Blueprint
#from . import routes

"""
import os
print(os.getcwd())
print(app.jinja_loader.searchpath)
"""

@dossier.route('/bof')
def mince():
    return render_template('dossier.html')

import os
from flask import render_template, redirect, url_for, flash

from .forms import Form
#from .models import TDemande 
#from ..auth.models import TUser
from .queries import get_dossier
from .methods import insertdoss
#from ..database import db
#from ..extensions import cache

from flask import render_template, redirect, url_for, flash, request, current_app
from flask_sqlalchemy import SQLAlchemy
#from db_file import db, login, login_manager, cache
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from flask_caching import Cache
#from dossier import dossier_bp

import sys
import platform
import flask
import re
import logging
import os
#from app import db
#from auth.forms import LoginForm, RegistrationForm
#from models import TUser
from flask import render_template, redirect, url_for, flash, request 
from flask_login import current_user, login_user, logout_user 
#import sqlalchemy as sa 
from urllib.parse import urlsplit
from flask import render_template
from flask_login import login_required
#from forms import *
#from forms import UserForm

from sqlalchemy import create_engine, MetaData
from sqlalchemy.orm import sessionmaker

#from db_init import db
from docxtpl import DocxTemplate
from flask import Response
from io import BytesIO
from flask import Flask, send_file

from datetime import datetime
from flask import Flask, request, redirect, url_for, session, flash
from flask import render_template
#from db_init import create_app
#from db_init import db
#from model import UserDetails, Product, OrderDetails, TCadastre, TParceldem, TCom2023, TCadastre, TPub, TUsager, TDemande, Country, City, Customer
#from app import db
#from .models import TDemande
#TCadastre, TParceldem, TCom2023, TCadastre, 
#from models import TUser
#from parsel import parsel_bp

from sqlalchemy.sql import text
from sqlalchemy import desc, asc, and_, select, text
#from model import Base

import flask
import flask_login
from flask import Blueprint
from flask_login import LoginManager
from flask import Flask, render_template
from flask_htmx import HTMX
#Base = db.session.query

# Create the logger
logger = logging.getLogger('failed_login_attempts')
logger.setLevel(logging.INFO)

# Create a file handler
handler = logging.FileHandler('failed_login_attempts.log')
logger.addHandler(handler)

from flask import render_template
from flask.blueprints import Blueprint
#from parsel import parsel_bp

from flask import Flask
import os.path

from sqlalchemy import Column, ForeignKey, Integer, String, create_engine, func, cast, Float 
from sqlalchemy.ext.declarative import declarative_base 
from sqlalchemy.orm import relationship,scoped_session,sessionmaker,aliased

from flask import Flask, render_template, request, jsonify, json
from flask_sqlalchemy import SQLAlchemy  
from wtforms import SelectField
from flask_wtf import FlaskForm

from flask import session
"""    
def setup_database(app):
    with app.app_context():
        db.create_all()
"""
from werkzeug.debug import DebuggedApplication
 
from flask_caching import Cache
import time

import sys
import platform
import flask
import re
import logging
import os
from datetime import datetime

#from database import db
from flask import Flask, request, redirect, url_for, session, flash
from flask import render_template
from flask.blueprints import Blueprint
from flask import current_app
from flask import Flask, session
from flask import request, flash

#from model import Base
import bcrypt

import os

import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.orm import relationship, Session
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.inspection import inspect
from sqlalchemy.dialects import postgresql
#from sqlalchemy import db.db.db.mapped_column, Table, Column, Bigdb.Integer, db.Integer, db.db.Text, db.Date, db.Boolean, db.db.db.String, ForeignKey
from sqlalchemy import desc
from flask_wtf import FlaskForm
from wtforms import StringField
#from flask_autodoc import Autodoc
#from flask_caching import Cache

#cache = Cache()

#from .cache import cache

#from ..zut.models import TParceldem

#@dossier_blueprint.route('/getdossier', methods=['GET', 'POST'])
@dossier.route('/getdossier', methods=['GET', 'POST'])
def getdossier():

    dossiers = get_dossier()
    if request.method == 'POST' :
        username=current_user.username
        user_id = current_user.id
        no_interne = str(request.form.get('no_interne'))
        no_pacage_demandeur = str(request.form.get('no_pacage_demandeur'))
        u_nom_raison_sociale = str(request.form.get('u_nom_raison_sociale'))
        session['no_interne'] = no_interne
        dossier_cible = session.get('no_interne')
        # Étape 1 : Récupérer les parcelles du dossier courant
        parcelles_courantes = db.session.query(TParceldem.par_idsuf) \
            .filter(TParceldem.par_nointerne == dossier_cible) \
            .distinct().all()
        idsuf_list = [p[0] for p in parcelles_courantes]

        # Étape 2 : Vérifier si chaque parcelle apparaît dans au moins un autre dossier
        parcelles_partagees = db.session.query(
            TParceldem.par_idsuf
        ).filter(
            TParceldem.par_idsuf.in_(idsuf_list),
            TParceldem.par_nointerne != dossier_cible
        ).distinct().all()

        # Étape 3 : Le nombre total de parcelles partagées
        nb_partagees = len(parcelles_partagees)
        
        #cache.set("current_no_interne", no_interne)
        #cache.add("current_no_interne", no_interne)
        
        no_interne = fetch_dossiers_by_no_interne(no_interne)

        fv = flask.__version__
        pv = platform.python_version()
        return render_template('dossier.html', fv=fv, pv=pv,
        dossiers=no_interne, no_pacage_demandeur=no_pacage_demandeur, u_nom_raison_sociale=u_nom_raison_sociale, username=username, user_id=user_id, nb_partagees=nb_partagees)

        db.session.commit()

    return redirect(url_for('dossier.dossier'))
    
@dossier.route('/insertdoss', methods=['POST'])
def insertdoss():
    if request.method == 'POST':
        no_interne = request.form['no_interne']
        date_complet = datetime.today().strftime('%d-%m-%y')
        user_id = request.form['user_id']
        
        # 🔧 Réaligner la séquence après l'insertion
        # Remplace bien par le nom exact de ta séquence et table
        seq_name = 'w_sadr_artaux.t_demande_idt_demande_seq'
        table_name = 'w_sadr_artaux.t_demande'

        db.session.execute(
            text(f"SELECT setval('{seq_name}', (SELECT COALESCE(MAX(idt_demande), 1) FROM {table_name}) + 1, false)")
        )
        db.session.commit()
        
        my_data = TDemande(
            no_interne=no_interne,
            date_complet=date_complet,
            user_id=user_id
        )

        db.session.add(my_data)
        db.session.commit()



        flash("Nouveau dossier ajouté avec succès !")
        return redirect(url_for('dossier.dossier'))

 
class Form(FlaskForm):
    no_interne = StringField('no_interne')

@dossier.route('/dossier')
#@login_required
# ‘/’ URL is bound with orders() function.
def dossier():
    # check whether user is logged or not
    #if 'user' in session:
    if current_user.is_authenticated:
        # if user has a active session get the username from the session
        name = current_user.username
        userId = str(current_user.id)
        user_dossiers = fetch_dossiers_by_id(userId)
        fv = flask.__version__
        pv = platform.python_version()
        #get_newnointerne = TDemande.query.filter_by(user_id=userId).order_by(desc(TDemande.no_interne)).first()
        #get_newnointerne = db.session.query(TDemande).filter_by(user_id=userId).order_by(desc(TDemande.no_interne)).first()
        #form = Form()
        string = str(str(TDemande.query.with_entities(TDemande.no_interne).order_by(TDemande.no_interne.desc()).first())[7:11])
        cleaned_value = string.replace("',", "")
        newnointerne = str(f"{int(cleaned_value)+1:04d}")
        x = len(newnointerne)
        date = datetime.now().strftime("%y/%m/%d")
        if x == 3:
            get_newnointerne = str(str('C22')+str(date[0:2])+str('0')+str(newnointerne))
            get_user_id = current_user.id
            return render_template('dossier.html', fv=fv, pv=pv,
            username=current_user.username, dossiers=user_dossiers, get_user_id=get_user_id, get_newnointerne=get_newnointerne)
            flash(date[0:2])
            flash(str(newnointerne))
            flash(x)
        #date.strftime("%d/%m/%y")
        get_newnointerne = str(str('C22')+str(date[0:2])+str(newnointerne))
        #get_user_id = session['user']['id']
        get_user_id = current_user.id
        flash(date[0:2])
        flash('test :' , str(newnointerne))
        flash(x)

flartaux/dossier/templates/dossier/_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Beta x Django</h1>

{% endblock content %}

flartaux/dossier/templates/dossier/accessibility.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Déclaration d’accessibilité</h1>

<p><span>Notre organisation</span> s’engage à rendre son service accessible, conformément à l’article 47 de la loi n° 2005-102 du 11 février 2005.</p>
<p>Cette déclaration d’accessibilité s’applique à <strong>ce service</strong>.</p>
<h2>État de conformité</h2>
<p>
	<strong>Notre site</strong> est 
	<strong><span data-printfilter="lowercase">non conforme</span></strong> avec le <abbr title="Référentiel général d’amélioration de l’accessibilité">RGAA</abbr>. <span>Le site n’a encore pas été audité.</span>
</p>
<h2>Voie de recours</h2>
<p>Cette procédure est à utiliser dans le cas suivant&nbsp;: vous avez signalé au responsable du site internet un défaut d’accessibilité qui vous empêche d’accéder à un contenu ou à un des services du portail et vous n’avez pas obtenu de réponse satisfaisante.</p>
<p>Vous pouvez&nbsp;:</p>
<ul>
	<li>Écrire un message au <a href="https://formulaire.defenseurdesdroits.fr/">Défenseur des droits</a></li>
	<li>Contacter <a href="https://www.defenseurdesdroits.fr/saisir/delegues">le délégué du Défenseur des droits dans votre région</a></li>
	<li>Envoyer un courrier par la poste (gratuit, ne pas mettre de timbre)&nbsp;:<br>
	Défenseur des droits<br>
	Libre réponse 71120 75342 Paris CEDEX 07</li>
</ul>
<hr>
<p>
	Cette déclaration d’accessibilité a été créé le <span>14 décembre 2022</span> grâce au <a href="https://betagouv.github.io/a11y-generateur-declaration/#create">Générateur de Déclaration d’Accessibilité de BetaGouv</a>.
</p>

{% endblock content %}

flartaux/dossier/templates/dossier/dossier.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products - Mobile Market</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
</head>
    {% include 'header.html' %}

{% block content %}

<body>
  <div class="container">
    <div class="table-row">
     <div class="table-cell" max-width=30px>
	 
                <h6>Pour créer un nouveau dossier, cliquer sur ce bouton : <button type="button"  class="btn btn-success float-right"
                data-toggle="modal" data-target="#mymodal">Créer un nouveau dossier</button> </h2>
				<br>
				<br>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                 
    {% for message in messages %}
                <div class="alert alert-success alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>
                {{message}}
                </div>
                {% endfor %}
     
                {% endif %}
                {% endwith %}	 
	   <div id="mymodal" class="modal fade" role="dialog">
      <div class="modal-dialog">
     <div class="modal-content">
    <div class="modal-header"><h4 class="modal-title">Ajouter ce nouveau dossier</h4></div>
    <div class="modal-body">
     <form action="{{url_for('dossier.insertdoss')}}" method="POST" name="no_interne">
      <div class="form-group">
       <label>no_interne:</label>
       <input type="text" class="form-control" name="no_interne" required
               value="{{get_newnointerne}}"/>
      </div>
      <div class="form-group">
       <label>user_id:</label>
       <input type="text" class="form-control" name="user_id" required
               value="{{get_user_id}}"/>
      </div>
      <div class="form-group">
      <button class="btn btn-primary" type="submit">Ajouter ce nouveau dossier</button>
      </div>
     </form>
    </div>
    <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Abandonner la création de ce dossier</button>
    </div>
   </div>
   </div>
  </div>

	 
	 
<span>Vous avez sélectionné<br>{% for dossier in dossiers %}{% if loop.index == 1 %}{{ loop.length }}{% endif %}{% endfor %} dossier(s) :</span>
     <div class="form-inline">
{% for dossier in dossiers %}
	{% if loop.length == 1 %}
		<span>Vous avez sélectionné<br>le dossier ci-dessous.</span>
				<br><br><form action="/getdossier" method="post" name="no_interne">
            <input type="hidden" name="no_interne" value="{{dossier['no_interne']}}">
            <button type="submit" class="getdossier-button">{{ dossier.no_interne }}</button>
<br><a href="/bof">Sélectionner des parcelles pour ce dossier</a></li>

{% if nb_partagees > 0 %}
  <div class="alert alert-info my-3" role="alert" style="background-color: #dc3545; color: white;">
    <strong>{{ nb_partagees }}</strong> parcelle(s) du dossier courant sont partagées avec au moins un autre dossier.
  </div>
<a href="/control">Contrôle : voir les parcelles en concurrence ou successives pour ce dossier</a></li>
  
{% endif %}

        </form>
	{% else %}
		
		<form action="/getdossier" method="post" name="no_interne">
            <input type="hidden" name="no_interne" value="{{dossier['no_interne']}}">
            <button type="submit" class="getdossier-button">{{ dossier.no_interne }}</button>
        </form>
	{% endif %}
{% endfor %}
        </div>
        </div>
{% endblock %}
{% extends "layout.html"%}
{%block body%}

    <div class="container orders">

        <div class="order-list">
            {% for dossier in dossiers %}
			    {% if loop.length > 1 %}
					{% if loop.index == 1 %}
						<span>Merci de bien vouloir sélectionner 
						un dossier dans la liste de gauche
						pour en afficher les détails.</span>
					{% endif %}
				{% else %}
            <div class="order">
                <p>N°Dossier : {{ dossier.no_interne }}</p>
            <p>Date de dépôt : {{ dossier.date_de_depot }}</p>
			<p>Numéro pacage du demandeur : {{ dossier.no_pacage_demandeur }}</p>
			<p>Raison sociale du demandeur : {{ dossier.u_nom_raison_sociale }}</p>
            </div>
				{% endif %}
            {% endfor %}
        </div>

<script src="{{ url_for('static', filename='js/script.js') }}"></script>
      </div>
    </div>
  </div>
  </body>

{%endblock%}
</html>

flartaux/dossier/templates/dossier/header.html
<header class="header">
        <center><h1><a href="/">FLARTAUX 0.0.1 sous langage Python version {{pv}} cadriciel Flask version {{fv}}</a></h1></center>
    <div class="container">
        <nav>
            <ul>
                <li></li>
				<li><a role="button" class="btn btn-primary btn-lg" href="/export_pandas_excel">export_pandas_excel</a></li>
				<li><a role="button" class="btn btn-primary btn-lg" href="/excel_pivot_conc">contrôle</a></li>
				<li><a role="button" class="btn btn-primary btn-lg" href="/excel">excel</a></li>
				<li><a role="button" class="btn btn-primary btn-lg" href="/mailmerge">word</a></li>
                <li><a href="/bof">parcelles</a></li>
                <li><a href="/dossier">Dossier</a></li>
				<li><a href="/templdocx">Publipostage</a></li>
                <li><a href="/book_list">Publicité foncière</a></li>
                <li><a href="/fiche">Fiche</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/">Home</a></li>
                {% if not username%}
                <li><a href="/login">Login</a></li>
                <li><a href="/register">Registration</a></li>
                {% else %}
                <li><a href="/orders">Orders</a></li>
                <li><a href="/password-update">Update Password </a></li>
                <li>|</li>
                <li>Bonjour, {{username}}</li>
                <li><a href="/logout">Logout</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

flartaux/dossier/templates/dossier/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask APP Crud with Postgres</title>
    <!--   Bootstrap CSS -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/dataTables.bootstrap4.css')}}">

    <!-- DataTables -->
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.bootstrap4.js"></script>

    <!-- Custom CSS for changing hover color -->
    <style>
    .dropdown-item:hover {
        color: black !important;
    }
    </style>


</head>
<body>

  <div class="container p-4">
    {%block body%}
      {% endblock %}
  </div>
  <script>new DataTable('#example');</script>

</body>
</html>

flartaux/dossier/templates/dossier/pivot.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Pivot Table</title>
</head>
<body>
    <table border="1">
        <thead>
            <tr>
                <th>par_idsuf</th>
                {% for key in keys %}
                    <th>{{ key }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
                <tr>
                    <td>{{ row.par_idsuf }}</td>
                    {% for key in keys %}
                        <td>{{ row['col_' + key] }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>