flartaux/parsel/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app, session
parsel = Blueprint('parsel', __name__)
from . import parsel
#from . import routes
#from jinja2 import Environment
from flask_caching import Cache
import os
from flask import render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
#from . import parsel_bp
#parsel_bp = Blueprint('parsel', __name__, template_folder='/templates/parsel')
from .forms import Form
from .queries import fetch_dossiers_by_no_interne, fetch_dossiers_by_id, get_parcelle_by_idsuf, get_all_t_demande, get_all_parcelles, get_all_parceldem, get_all_t_com2023, fetch_sections_by_commune
#def fetch_dossiers_by_no_interne(no_interne), def fetch_dossiers_by_id(user_id), def fetch_orders_by_id(user_id), def fetch_orders_by_order_id(order_id), def get_parcelle_by_idsuf(idsuf), def get_all_t_demande(), def get_all_parcelles(),def get_all_parceldem(), def get_all_t_com2023(), def fetch_sections_by_commune(idcom)
from .methods import total_balance, header
from ..database import db
from ..extensions import cache
#from .models import TParceldem, TCom2023, TCadastre

@parsel.route('/bof')
#@login_required
def zut():
    return render_template('templates/test.html')
"""
Module docstring: This module provides functionality
for Cellmart wesite developed using flask.
"""
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_sqlalchemy import SQLAlchemy

#from db_file import db, login, login_manager, cache

from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user

#from parsel import parsel_bp
#, db, login_manager, cache


import os
"""
from flask import Flask, Blueprint, render_template

templates = os.path.join(os.path.dirname(__file__), 'templates')

parsel_bp = Blueprint('parsel', __name__, template_folder='templates', static_folder='static')
"""
import sys
import platform
import flask
import re
import logging
import os
#from app import db
#from auth.forms import LoginForm, RegistrationForm
#from models import TUser
from flask import render_template, redirect, url_for, flash, request 
from flask_login import current_user, login_user, logout_user 
import sqlalchemy as sa 
from urllib.parse import urlsplit
from flask import render_template
from flask_login import login_required
#from forms import *
#from forms import UserForm

from sqlalchemy import create_engine, MetaData
from sqlalchemy.orm import sessionmaker

#from db_init import db
from docxtpl import DocxTemplate
from flask import Response
from io import BytesIO
from flask import Flask, send_file

from datetime import datetime
from flask import Flask, request, redirect, url_for, session, flash
from flask import render_template
#from db_init import create_app
#from db_init import db
#from model import UserDetails, Product, OrderDetails, TCadastre, TParceldem, TCom2023, TCadastre, TPub, TUsager, TDemande, Country, City, Customer
#from app import db
#from models import TUser
#from parsel import parsel_bp

from sqlalchemy.sql import text
from sqlalchemy import desc, asc, and_, select, text
#from model import Base

import flask
import flask_login
from flask import Blueprint
from flask_login import LoginManager
from flask import Flask, render_template
from flask_htmx import HTMX
#Base = db.session.query

# Create the logger
logger = logging.getLogger('failed_login_attempts')
logger.setLevel(logging.INFO)

# Create a file handler
handler = logging.FileHandler('failed_login_attempts.log')
logger.addHandler(handler)
'''
app = create_app(os.getenv("CONFIG_MODE"))
app.secret_key = '12345678'
'''
#from database import db
from flask import render_template
#from flask.blueprints import Blueprint
#from parsel import parsel_bp

"""
parsel = Blueprint('parsel_bp', __name__,
                 template_folder='../templates',
                 static_folder='../static')
"""                
   
#from database import db
from flask import Flask
import os.path


from sqlalchemy import Column, ForeignKey, Integer, String, create_engine, func, cast, Float 
from sqlalchemy.ext.declarative import declarative_base 
from sqlalchemy.orm import relationship,scoped_session,sessionmaker,aliased

from flask import Flask, render_template, request, jsonify, json
from flask_sqlalchemy import SQLAlchemy  
from wtforms import SelectField
from flask_wtf import FlaskForm

from flask import session
    

from werkzeug.debug import DebuggedApplication
   
from flask_caching import Cache
import time

#cache = Cache(app)

@parsel.route('/pay', methods=["POST","GET"])
def pay():    
    t_parceldem = get_all_parceldem()
    #t_parceldem = db.session.query(TParceldem).filter(TParceldem.par_nointerne.like("C22160001")).all()
    cache.set("commune", str("Sélectionner une commune"))    
    if request.method == 'POST':
        commune = cache.get("commune")
        section = cache.get("section")
        parcelles = cache.get("parcelles")
        form = Form()
        '''
        commune = db.session.query(TCom2023).filter_by(com=form.commune.data).first()
        cache.set("commune", db.session.query(TCom2023).filter_by(com=form.commune.data).first())
        section = db.session.query(TCadastre).filter_by(ccosec=form.section.data).first()
        cache.set("section", db.session.query(TCadastre).filter_by(ccosec=form.section.data).first())
        #parcelles = db.session.query(TCadastre.idsuf).where(and_((TCadastre.idcom==format(commune.com),(TCadastre.ccosec==format(section.ccosec))))).all()
        parcelles = db.session.query(TCadastre.idsuf).where(and_((TCadastre.idcom==commune.com),(TCadastre.ccosec==section.ccosec))).all()
        cache.set("parcelles", db.session.query(TCadastre.idsuf).where(and_((TCadastre.idcom==commune.com),(TCadastre.ccosec==section.ccosec))).all())
        '''
        #form.commune.choices = [(commune.com, commune.libelle) for commune in db.session.query(TCom2023).filter_by(dep='22').all()]
        form.commune.choices = [("", "Sélectionner une commune")]+[(commune.com, commune.libelle) for commune in db.session.query(TCom2023).filter_by(dep='22').all()]
            
        t_com2023 = get_all_t_com2023()
        #parcelles = get_all_parcelles()
        #com='search_com2023_id'
        #sections = fetch_sections_by_commune('22278')
   
        fv = flask.__version__
        pv = platform.python_version()
        # check whether user is logged or not
    
        # Get the order details from the form
        #user_id = session['user']['id']
        par_idsuf = request.form.get('parcelle_idsuf')
        #quantity = int(request.form.get('quantity'))
        #product = get_product_by_id(product_id)
        #parcelle = get_parcelle_by_idsuf(idsuf)
        #price = float(product.price)
        #total = price * quantity
        no_interne = str(session.get('no_interne'))
        #par_surface = str('1')
        #user = session.query(User.name).filter(User.id == 1).first()
        #par_surface = session.query(TCadastre.dcntsf).filter(TCadastre.idsuf == par_idsuf).first()
        #user = User.query.filter_by(username=username).first()
        #par_surface = db.session.query(TCadastre.dcntsf).filter(TCadastre.idsuf == par_idsuf).first()
        import re        
        par_surface = re.sub(r'\D', '', str(db.session.query(TCadastre.dcntsf).filter(TCadastre.idsuf == par_idsuf).first()))
        #par_surface = re.sub(r'\D', '', str(par_surface))
        print('par_surface:', par_surface)
        # Save the order details to the DB
        t_parceldem = TParceldem(par_idsuf=par_idsuf,
                                     par_nointerne=no_interne, par_surface=par_surface)
        
    newpar = db.session.query(TParceldem).filter(and_(TParceldem.par_idsuf == par_idsuf, TParceldem.par_nointerne == no_interne)).first()

    if newpar is not None:
        #flash('Parcelle {par_idsuf} déja sélectionnée.')
        #return 'hello'        
        #return flash('La parcelle : %s, a déjà été demandée dans le dossier : %s' % (par_idsuf, "C22160001"))
        message = "Attention : cette parcelle " + str(par_idsuf) + " a déjà été sélectionnée. Merci d'en sélectionner une autre."  # Concatenation
        flash(message, 'danger')
        return render_template("index.html", t_parceldem=get_all_parceldem(),
        parcelles=parcelles, form=form, pv=pv, fv=fv,
        username=current_user.username)  # return index.html with username of logged user

    else:
        #return 'hello'

        db.session.add(t_parceldem)
        db.session.commit()
        #print(t_parceldem)
        #return redirect(url_for('parsel.home'))
        
        no_interne = str(session.get('no_interne'))
        bal = db.session.query(text("""sum(cast(par_surface as int)) FROM t_parceldem where par_nointerne=:numdoss""")).params(numdoss=no_interne).all()

        import re

        balance = re.sub(r'\D', '', str(bal))

        num_str = int(str(balance)) / 10000
        print('num_str :', num_str)
  
        balance = f"{str(num_str).replace('.', ',')} ha"        
        
        return render_template("index.html", balance=balance, t_parceldem=get_all_parceldem(),
        parcelles=parcelles, form=form, pv=pv, fv=fv,
        username=current_user.username)  # return index.html with username of logged user


@parsel.route('/test', methods=['GET', 'POST'])
#@login_required
#@current_app.cache.cached(timeout=60)  # Cache the view for 60 seconds
def test():
    # Explicitly push the app context
    #with app.app_context():
    # Simulating some dynamic data
    dynamic_data = "This is a dynamically generated value that will be cached."
    return render_template('test.html', dynamic_data=dynamic_data)
    
        
#insert data to mysql database via html forms
@parsel.route('/insert', methods=['GET', 'POST'])
def insert():
    if request.method == 'POST':
        '''

flartaux/parsel/templates/parsel/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>WebAppName</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">WebAppName</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
                    </li>

                </ul>

                <ul class="navbar-nav mb-2 mb-lg-0">

                    {% if current_user.is_anonymous %}
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{{ url_for('auth.login') }}"">Login</a>
                        </li>
                    {% else %}

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{{ url_for('main.index')}} ">{{ current_user.username }}</a>
                        </li>

                        {% if current_user.is_admin() %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{{ url_for('admin.admin_home') }}">Admin</a>
                            </li>
                        {% endif %}

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{{ url_for('auth.logout')}} ">Logout</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'message' %}
                        <div class="alert alert-info" role="alert">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
    </script>
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $(".alert").fadeOut("slow");
            }, 5000); // 5 seconds x 1000 milliseconds
        });
    </script>
</body>
</html>

flartaux/parsel/templates/parsel/header.html
<header class="header">
        <center><h1><a href="/">FLARTAUX 0.0.1 sous langage Python version {{pv}} cadriciel Flask version {{fv}}</a></h1></center>
    <div class="container">
        <nav>
            <ul>
                <li></li>
				<li><a role="button" class="btn btn-primary btn-lg" href="/export_pandas_excel">export_pandas_excel</a></li>
				<li><a role="button" class="btn btn-primary btn-lg" href="/excel_pivot_conc">contrôle</a></li>
				<li><a role="button" class="btn btn-primary btn-lg" href="/excel">excel</a></li>
				<li><a role="button" class="btn btn-primary btn-lg" href="/mailmerge">word</a></li>
                <li><a href="/parsel">parsel</a></li>
                <li><a href="/dossier">Dossier</a></li>
                <li><a href="/groupsel">Propriétaires</a></li>
                <li><a href="/book_list">Publicité foncière</a></li>
                <li><a href="/fiche">Fiche</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/">Home</a></li>
                {% if not username%}
                <li><a href="/login">Login</a></li>
                <li><a href="/register">Registration</a></li>
                {% else %}
                <li><a href="/orders">Orders</a></li>
                <li><a href="/password-update">Update Password </a></li>
                <li>|</li>
                <li>Bonjour, {{username}}</li>
                <li><a href="/logout">Logout</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

flartaux/parsel/templates/parsel/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products - Mobile Market</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
</head>
<!--<div class="blue-div">-->
    {% include 'parsel/header.html' %}

                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                 
    {% for message in messages %}
                <div style = "background-color: red text-color: yellow" class="alert alert-success alert-warning alert-dismissible fade show" role="error">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>
                {{message}}
                </div>
                {% endfor %}
     
                {% endif %}
                {% endwith %}
	
{% block content %}
<body>

    <div class="table-row">
     <div class="table-cell">
	        <div class="card-body">
		
			<form method="POST">
				{{ form.csrf_token}}  
				<div class="form-group">
				<label for="email">Commune:</label>
				{{ form.commune(class="form-control") }}
				</div>
				<div class="form-group">
				<label for="email">section:</label>
				{{ form.section(class="form-control")}}
				</div>
				<input type="submit" value="slkdfjkjdlflsFiltrer les parcelles" class="btn btn-success" btn-lg>
  </form>


                <h6>En cas de parcelle manquante : <button type="button"  class="btn btn-success float-right"
                data-toggle="modal" data-target="#mymodal">Ajouter une parcelle manquante</button> </h2>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                 
    {% for message in messages %}
                <div class="alert alert-success alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>
                {{message}}
                </div>
                {% endfor %}
     
                {% endif %}
                {% endwith %}
  
                <table class="table table-hover table-striped">
                   {% for TCadastre in t_cadastre %}
     <!-- Modal Edit Employee-->
     <div id="modaledit{{TCadastre.idt_cadastre}}" class="modal fade" role="dialog">
        <div class="modal-dialog">
        <div class="modal-content">
       <div class="modal-header"><h4 class="modal-title">Update Information</h4></div>
        <div class="modal-body">
        <form action="{{url_for('parsel.update')}}" method="POST">
         <div class="form-group">
          <label>Name:</label>
          <input type="hidden"  name="idt_cadastre" value="{{TCadastre.idt_cadastre}}">
          <input type="text" class="form-control" name="name" value="{{TCadastre.idsuf}}">
         </div>
         <div class="form-group">
          <button class="btn btn-primary" type="submit">Update</button>
         </div>
        </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
      </div>
     </div> 
     {% endfor %}
    </table>
   </div>
  
  <!-- Modal Add Employee-->
  <div id="mymodal" class="modal fade" role="dialog">
      <div class="modal-dialog">
     <div class="modal-content">
    <div class="modal-header"><h4 class="modal-title">Ajouter une parcelle manquante</h4></div>
    <div class="modal-body">
     <form action="{{url_for('parsel.insert')}}" method="POST">
      <div class="form-group">
       <label>idsuf:</label>
       <input type="text" class="form-control" name="idsuf" required="1">
      </div>
	  <div class="form-group">
       <label>ccosec:</label>
       <input type="text" class="form-control" name="ccosec" required="1">
      </div>
	  <div class="form-group">
       <label>idcom:</label>
       <input type="text" class="form-control" name="idcom" required="1">
      </div>
      <div class="form-group">
      <button class="btn btn-primary" type="submit">Ajouter une parcelle manquante</button>
      </div>
     </form>
    </div>
    <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Abandonner l'ajout</button>
    </div>
   </div>
   </div>
  </div>


     <div class="form-inline">
          {% for parcelle in parcelles %}
<form action="/pay" name="idsuf" method="post">
            <input type="hidden" name="parcelle_idsuf" value="{{parcelle['idsuf']}}">

            <button type="submit" class="pay-button">{{ parcelle.idsuf }}</button>
	

        </form>	
          {% endfor %}
        </div>
        </div>		

<script>
commune_select = document.getElementById('commune');
section_select = document.getElementById('section');
parcelle_select = document.getElementById('parcelle');
 
commune_select.onchange = function(){
 history.pushState({}, null, '/parsel');
 commune = commune_select.value;
 <!-- alert(commune); --> 
 fetch('section/' + commune).then(function(response){
  response.json().then(function(data) {
   optionHTML = '';
   for (section of data.sectioncommune) {
    optionHTML += '<option value="' + section.ccosec +'">' + section.ccosec + '</option>'
   }
   section_select.innerHTML = optionHTML;
  });
 });
}
section_select.onchange = function(){
 parcelle = section_select.value; 
 fetch('parcelle/' + parcelle).then(function(response){
  response.json().then(function(data) {
   optionHTML = '';
   for (parcelle_rs of data.parcellelist) {
    optionHTML += '<option value="' + parcelle_rs.ccosec +'">' + parcelle_rs.ccosec + '</option>'
   }
   parcelle_select.innerHTML = optionHTML;
  });
 });
}
</script>
				
				
{% endblock %}
{% extends "parsel/layout.html"%}
{%block body%}

      <div class="table-cell">	  
   
            <table id="example" class= "table table-hover table-bordered">

                <thead>
				        
                    <tr class="bg-dark text-white">
                        <th scope="col">Course Name</th>
                        <th scope="col">Action</th>
					</tr>
                </thead>
				<h1><p>balance : {{balance}}</p></h1>
                <tbody>
				
                    {%for TParceldem in t_parceldem%}
					
                    <tr>
                        <!-- data.index is used so that table has S.no. even when some
                        id get deleted from the table-->

                        <td width="3900" >{{TParceldem.par_idsuf}}</td>
                        <td width="150" >
                            <!-- to get the value for button we need real ID not index -->

                            <a href="/delete/{{TParceldem[0]}}" class="btn btn-danger btn-sm ">Delete</a>
                        </td>
					</tr>
                    {%endfor%}
                </tbody>
            </table>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>
      </div>
    </div>

  </body>

{%endblock%}
<!--</div>-->
</html>

flartaux/parsel/templates/parsel/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask APP Crud with Postgres</title>
    <!--   Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.bootstrap4.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/dataTables.bootstrap4.css')}}">

    <!-- DataTables -->
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.0.5/js/dataTables.bootstrap4.js"></script>

    <!-- Custom CSS for changing hover color -->
    <style>
    .dropdown-item:hover {
        color: black !important;
    }
    </style>


</head>
<body>

  <div class="container p-4">
    {%block body%}
      {% endblock %}
  </div>
  <script>new DataTable('#example');</script>

</body>
</html>

flartaux/parsel/templates/parsel/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Caching Example</title>
</head>
<body>
    <h1>Flask Caching Example</h1>
    <p>Dynamic Data: {{ dynamic_data }}</p>
    <p>This page will be cached for 60 seconds. Refresh to see the caching in action!</p>
</body>
</html>